@hostname = localhost
@port = 8085
@host = {{hostname}}:{{port}}
@token = token123


GET http://{{host}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

GET http://{{host}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

POST http://{{host}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": "1234567890",
    "birthday": "1990-01-01"
}

###

PUT http://{{host}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",
    "phone": "1234567890",
    "birthday": "1990-01-01"
}

###

DELETE http://{{host}}/api/v1/users/2
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

### Accounts

GET http://{{host}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

GET http://{{host}}/api/v1/accounts/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

POST http://{{host}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
    "name": "Some User",
    "password": "password"
}


### Sessions
# @name login
POST http://{{host}}/api/v1/session
Content-Type: application/json

{
    "name": "Some User",
    "password": "password"
}
