@hostname = localhost
@port = 8085
@host = {{hostname}}:{{port}}
@token = token123


GET http://{{host}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET http://{{host}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{token}}
###

POST http://{{token}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com"
}

###

PUT http://{{host}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "Jane",
    "last_name": "Doe",
    "email": "jane.doe@example.com"
}

###

DELETE http://{{host}}/api/v1/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

### Accounts

GET http://{{host}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET http://{{host}}/api/v1/accounts/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://{{host}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some User",
    "password": "password"
}